version: '3.8'

services:
  postgres:
    build:
      context: .
      # Allows the build process to find any file involved in a COPY,
      # or similar commands.
      dockerfile: Dockerfile
    container_name: postgres_piscineds
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
