version: '3.8'

services:
  postgres:
    image: postgres:latest # Contains the psql client/interface, which we will use later.
    container_name: postgres_piscineds
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
