version: '3.8'

services:
  postgres:
    image: postgres:latest # Contains the psql client/interface, which we will use later.
    container_name: postgres_piscineds
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nstoutze
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"


volumes:
  postgres_data:
    driver: local
