FROM postgres:latest

ARG SCRIPTS_DIR
ARG POSTGRES_CONTAINER
ARG PG_HBA_CONF
ARG INIT_PG_HBA_SH

ENV SCRIPTS_DIR=${SCRIPTS_DIR}
ENV POSTGRES_CONTAINER=${POSTGRES_CONTAINER}
ENV PG_HBA_CONF=${PG_HBA_CONF}
ENV INIT_PG_HBA_SH=${INIT_PG_HBA_SH}

COPY ${SCRIPTS_DIR}/${POSTGRES_CONTAINER}/${PG_HBA_CONF} /docker-entrypoint-initdb.d/${PG_HBA_CONF}
# The new pg_hba.conf which we copy into the container is designed
# to make authentication mandatory during any connection to the db.
# Read the init_pg_hba.conf notes to learn more.

COPY ${SCRIPTS_DIR}/${POSTGRES_CONTAINER}/${INIT_PG_HBA_SH} /docker-entrypoint-initdb.d/${INIT_PG_HBA_SH}
RUN chmod +x /docker-entrypoint-initdb.d/${INIT_PG_HBA_SH}
# This directory docker-entrypoint-initdb.d is used to
# customize how the container is started.
# Any file .sql .sh or .sql.gz is run automatically

# Remind to docker-compose build <container_name>
# to get an image, and then a container
# with any modification you would do in this Dockerfile